services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

    networks:
      - app-network

    

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "8080"
    networks:
      - app-network


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/access_control
    depends_on:
      - db
    networks:
      - app-network
    

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker exec -it db-1 psql -U postgres

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    driver: bridge