name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Simple success step
      run: echo "This is a successful step!"
